name: CloudSim Build and Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Compile CloudSim project
      run: |
        mkdir -p bin
        javac -cp lib/cloudsim-3.0.3.jar -d bin src/PriorityTaskScheduler.java

    - name: Run simulation
      run: |
        java -cp "lib/cloudsim-3.0.3.jar:bin" PriorityTaskScheduler
